# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuwFLPFK8rka45_B1M1YE89WCTrZgv5Z
"""

! pip install streamlit -q

!pip install plotly

# Install necessary libraries
!pip install plotly dash

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501